# Generated by Django 3.0 on 2019-12-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bagian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bagian', models.CharField(max_length=100)),
                ('sub_bagian', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Bagian',
                'verbose_name_plural': 'Bagian',
                'ordering': ['nama_bagian', 'sub_bagian'],
            },
        ),
        migrations.AlterField(
            model_name='notebook',
            name='jawaban',
            field=models.TextField(null=True, verbose_name='Jawaban'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='kategori',
            field=models.CharField(max_length=100, verbose_name='Kategori Pertanyaan'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='nama',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='no_telp',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomor Telp'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='pertanyaan',
            field=models.TextField(null=True, verbose_name='Pertanyaan'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='profesi',
            field=models.CharField(max_length=100, null=True, verbose_name='Profesi'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='sub_bagian',
            field=models.CharField(max_length=100, null=True, verbose_name='Sub Bagian'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='bagian',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook.bagian', verbose_name='Bagian'),
        ),
    ]
