# Generated by Django 3.0 on 2019-12-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_notebook_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='bagian',
            field=models.ForeignKey(default=None, help_text='Sub Bagian yang bertanggung jawab', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook.bagian', verbose_name='Bagian'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='jawaban',
            field=models.TextField(help_text='Solusi atau jawaban', null=True, verbose_name='Jawaban'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='kategori',
            field=models.CharField(help_text='Kategori Pertanyaan', max_length=100, verbose_name='Kategori Pertanyaan'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='keterangan',
            field=models.BooleanField(default=False, help_text='Keterangan Masalah selesai atau belum selesai', verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='nama',
            field=models.CharField(help_text='Nama Pengunjung', max_length=100, null=True, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='no_telp',
            field=models.CharField(help_text='Nomor Handphone untuk dihubungi', max_length=50, null=True, verbose_name='Nomor Telp'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='pertanyaan',
            field=models.TextField(help_text='Pertanyaan Pengunjung', null=True, verbose_name='Pertanyaan'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='prioritas',
            field=models.CharField(help_text='Prioritas Masalah', max_length=100, null=True, verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='profesi',
            field=models.CharField(help_text='Profesi Pengunjung', max_length=100, null=True, verbose_name='Profesi'),
        ),
    ]
