# Generated by Django 3.1.7 on 2021-04-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0002_dokumen_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sikept.dokumen'),
        ),
        migrations.AddField(
            model_name='order',
            name='pts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sikept.pts'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ditolak', 'Ditolak'), ('Dikirim', 'Dikirim')], max_length=200, null=True),
        ),
    ]
