# Generated by Django 3.1.7 on 2021-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0004_auto_20210414_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='pts',
            name='Provinsi',
            field=models.CharField(choices=[('NTB', 'Nusa Tenggara Barat'), ('Bali', 'Bali')], max_length=200, null=True),
        ),
    ]
