# Generated by Django 3.1.7 on 2021-04-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0006_auto_20210420_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yayasan',
            old_name='email_yys',
            new_name='email_yayasan',
        ),
        migrations.RenameField(
            model_name='yayasan',
            old_name='name_yys',
            new_name='name_yayasan',
        ),
        migrations.RenameField(
            model_name='yayasan',
            old_name='phone_yys',
            new_name='phone_yayasan',
        ),
    ]
