# Generated by Django 3.1.7 on 2021-04-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0007_auto_20210420_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yayasan',
            old_name='name_yayasan',
            new_name='nama_yayasan',
        ),
        migrations.AddField(
            model_name='pts',
            name='nama_yayasan',
            field=models.ManyToManyField(to='sikept.Yayasan'),
        ),
    ]
