# Generated by Django 3.1.7 on 2021-04-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0008_auto_20210420_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pts',
            name='nama_yayasan',
        ),
        migrations.AddField(
            model_name='pts',
            name='nama_yayasan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sikept.yayasan'),
        ),
    ]
