# Generated by Django 3.1.7 on 2021-04-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0009_auto_20210422_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumen',
            old_name='name',
            new_name='nomor',
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='category',
            field=models.CharField(choices=[('SK', 'SK'), ('Legalitas', 'Legalitas'), ('Akta', 'Akta')], max_length=200, null=True),
        ),
    ]
