# Generated by Django 3.1.7 on 2021-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0011_auto_20210424_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='pts',
            name='status_pts',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Alih Bentuk', 'Alih Bentuk'), ('Tutup', 'Tutup')], max_length=200, null=True),
        ),
    ]
