# Generated by Django 3.1.7 on 2021-04-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0012_pts_status_pts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dokumen',
            new_name='nomor',
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='tanggal_surat',
            field=models.DateField(null=True),
        ),
    ]
