# Generated by Django 3.1.7 on 2021-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0017_auto_20210425_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='nomor',
            new_name='dokumen',
        ),
    ]
