# Generated by Django 3.1.7 on 2021-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0019_auto_20210425_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Jenis',
            field=models.CharField(choices=[('Akta', 'Akta'), ('SK', 'SK'), ('Rekomendasi', 'Rekomendasi'), ('Surat', 'Surat')], max_length=200, null=True),
        ),
    ]
