# Generated by Django 3.1.7 on 2021-05-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0021_auto_20210501_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='nomor',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Jenis',
            field=models.CharField(choices=[('Akta', 'Akta'), ('SK Menkumham', 'SK Menkumham'), ('SK', 'SK'), ('Rekomendasi', 'Rekomendasi'), ('Surat', 'Surat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pts',
            name='status_pts',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Alih Bentuk', 'Alih Bentuk'), ('Tutup', 'Tutup'), ('Pembinaan', 'Pembinaan')], max_length=200, null=True),
        ),
    ]
