# Generated by Django 3.1.7 on 2021-05-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0022_auto_20210502_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='nomor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
